name: Main

on:
  push:
    branches:
      - main
    pull_request:
env:
  CGO_ENABLED: 0
  GOVERSION: 1.22.1
  GOLANGCI_LINT_VERSION: 1.57.2

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Check and get dependencies
        run: |
          go mod download
          go mod tidy
          git diff --exit-code go.mod
          git diff --exit-code go.sum

      - name: Build the project
        run: |
          mkdir -p ./bin
          go build -o ./bin ./...

      - name: Archive build output
        uses: actions/upload-artifact@v3
        with:
          name: built-project
          path: ./bin/cmd

  tests:
    name: Tests
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: built-project
          path: ./bin/

      - name: Run tests
        run: go test -v ./...
